### ISSUE TITLE
Duplicate cursor names when using multiple triggers

### ISSUE THREAD

**Issue by kolkinn** [win7user10/Laraue.EfCoreTriggers#52]
Hi. I have two triggers on an entity, one `AfterInsert(t => t.Action(a => a.Update(...)))` and one `AfterUpdate(t => t.Action(a => a.Update(...)))`. These both get the same cursor name `Inserted<ENTITY_NAME>Cursor`.
This causes an error when I try to insert a row to the table:
> A cursor with the same name 'InsertedMyEntityCursor' already exists.

Am I doing something wrong, or should each trigger instead be gettting their own uniquely named cursor?

My simple scenario here is setting a CreatedDate after insert and ModifiedDate after update.

**Comment by Xriuk** [comment]
Apparently there's an option to make the cursor local, because now it seems global: [https://stackoverflow.com/a/3524875/2672235](https://stackoverflow.com/a/3524875/2672235)

I managed to fix that by creating a class cloned from `SqlServerTriggerVisitor` and [changing the cursor declaration](https://github.com/win7user10/Laraue.EfCoreTriggers/blob/master/src/Laraue.EfCoreTriggers.SqlServer/SqlServerTriggerVisitor.cs#L208) to
```
return $"DECLARE {cursorName} CURSOR LOCAL FOR";
```
then in the DbContext I replaced the service with mine:
```
protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder) {
    optionsBuilder.UseSqlServer(@"...").UseSqlServerTriggers(services => services.AddScoped<ITriggerVisitor, SqlServerTriggerVisitorFix>());
}
```

And it seems to work

**Comment by kolkinn** [comment]
Thank you for the workaround, @Xriuk!
It worked very well.
